"""Walk a :class:`QueryPlan` and build a SQLGlot ``Select`` AST.

Every :class:`PlanStep` becomes a named CTE whose alias follows a
deterministic ``step_000``, ``step_001`` pattern. The final outer
``SELECT`` references the root CTE and attaches the plan's
``ORDER BY`` / ``LIMIT``.

Nothing in this module reads the :class:`~osi.parsing.models.SemanticModel`
— see ``src/osi/codegen/README.md``. All input facts travel on the
plan's payloads (``source`` on :class:`SourcePayload`,
``child_source`` on :class:`EnrichPayload`).

The rendering is intentionally literal: one CTE per step keeps goldens
traceable, and :mod:`osi.codegen.cte_optimizer` is free to inline /
fold as a *post-step*.
"""

from __future__ import annotations

from sqlglot import expressions as exp

from osi.common.identifiers import Identifier
from osi.errors import ErrorCode, OSICodegenError
from osi.planning.algebra.operations import FilterMode, JoinType
from osi.planning.algebra.state import AggregateFunction, CalculationState, Column
from osi.planning.plan import (
    AddColumnsPayload,
    AggregatePayload,
    EnrichDerivedPayload,
    EnrichPayload,
    FilteringJoinPayload,
    FilterPayload,
    MergePayload,
    PlanOperation,
    PlanStep,
    ProjectPayload,
    QueryPlan,
    SourcePayload,
)
from osi.planning.prefixes import step_alias as _step_alias


def _ident(name: Identifier | str, *, table: str | None = None) -> exp.Column:
    """Wrap ``name`` as an :class:`sqlglot.expressions.Column`."""
    return exp.column(str(name), table=table, quoted=False)


def _qualify_columns(
    expression: exp.Expression,
    alias: str,
    *,
    home_logical_name: str | None = None,
) -> exp.Expression:
    """Rewrite every column reference to live under CTE ``alias``.

    Plan-level expressions refer to columns by their *logical* name —
    either bare (``amount``) or under a logical dataset qualifier
    (``orders.amount``). Inside a CTE every input column lives under
    the parent CTE's *physical* alias (``step_000``). Both forms must
    be remapped: bare columns gain the alias, and logical qualifiers
    are overwritten with the physical one.

    Overwriting a logical qualifier is intentional. ``orders`` is the
    user's name for the dataset, never the runtime table name; the
    transpiler is the layer that resolves the logical → physical
    mapping. Tests asserting on this behaviour live in
    ``tests/golden/test_sql_goldens.py`` and the enrich-renaming
    cases in ``tests/unit/codegen/test_transpiler.py``.

    Subqueries have their own scope — the columns inside a
    correlated subquery (generated by D-003 / D-015 home-grain
    aggregation) deliberately reference the *outer* table. The only
    column qualifier inside a subquery we touch is the home logical
    name itself (``home_logical_name``), since the surrounding step
    has aliased that table to ``alias``. Every other inner reference
    is left alone.
    """
    inside_subquery: set[int] = set()
    for sub in expression.find_all(exp.Subquery):
        for inner in sub.find_all(exp.Column):
            inside_subquery.add(id(inner))
    for col in expression.find_all(exp.Column):
        if id(col) in inside_subquery:
            if home_logical_name is None:
                continue
            current_table = col.table or ""
            if current_table.lower() != home_logical_name.lower():
                continue
        col.set("table", exp.to_identifier(alias))
    return expression


def _is_identity_column(expr: exp.Expression, name: str) -> bool:
    """Return True iff ``expr`` is a bare column reference whose name equals ``name``.

    Used by :func:`_render_source` to suppress redundant ``"x" AS "x"``
    aliases: when a field's expression is already the bare column name,
    emitting an alias adds visual noise without any semantic value.
    Comparison is case-insensitive to match identifier normalisation.
    """
    return (
        isinstance(expr, exp.Column)
        and not expr.table
        and (expr.name or "").lower() == name.lower()
    )


def _render_source(payload: SourcePayload, columns: tuple[Column, ...]) -> exp.Select:
    if not payload.source:
        raise OSICodegenError(
            ErrorCode.E5001_DIALECT_UNSUPPORTED,
            f"SOURCE step for {payload.dataset!r} has no physical source",
            context={"dataset": payload.dataset},
        )
    projections: list[exp.Expression] = []
    for col in columns:
        expr = col.expression.expr.copy()
        col_name = str(col.name)
        # Omit the alias when the expression is already a bare column
        # reference with the same name — ``"x" AS "x"`` adds no information.
        if _is_identity_column(expr, col_name):
            projections.append(expr)
        else:
            projections.append(exp.alias_(expr, col_name, quoted=False))
    return exp.select(*projections).from_(exp.to_table(payload.source))


def _pass_through(
    parent_alias: str,
    columns: tuple[Column, ...],
    alias_map: dict[Identifier, Identifier] | None = None,
) -> exp.Select:
    """Build a ``SELECT col[, ...] FROM parent_alias`` projection.

    If ``alias_map`` maps an internal column name to a user-visible
    output name, the projection emits ``col AS alias`` for that
    column (S-7 measure aliasing).
    """
    alias_map = alias_map or {}
    projections: list[exp.Expression] = []
    for c in columns:
        ident = _ident(c.name, table=parent_alias)
        alias = alias_map.get(c.name)
        if alias is not None and alias != c.name:
            ident = exp.alias_(ident, exp.to_identifier(str(alias), quoted=False))
        projections.append(ident)
    return exp.select(*projections).from_(exp.to_table(parent_alias))


def _render_filter(
    parent_alias: str, payload: FilterPayload, parent_columns: tuple[Column, ...]
) -> exp.Select:
    sel = _pass_through(parent_alias, parent_columns)
    predicate = _qualify_columns(payload.predicate.expr.copy(), parent_alias)
    return sel.where(predicate)


def _and(conds: list[exp.Expression]) -> exp.Expression:
    result = conds[0]
    for c in conds[1:]:
        result = exp.And(this=result, expression=c)
    return result


def _render_enrich(
    parent_alias: str,
    payload: EnrichPayload,
    parent_columns: tuple[Column, ...],
) -> exp.Select:
    child_alias = f"{parent_alias}_r"
    join_kind = "INNER" if payload.join_type is JoinType.INNER else "LEFT"
    parent_projs: list[exp.Expression] = [
        _ident(c.name, table=parent_alias) for c in parent_columns
    ]
    child_projs: list[exp.Expression] = []
    for col in payload.child_columns:
        child_expr = _qualify_columns(
            col.expression.expr.copy(),
            child_alias,
            home_logical_name=str(payload.child_dataset),
        )
        child_projs.append(exp.alias_(child_expr, str(col.name), quoted=False))
    sel = exp.select(*parent_projs, *child_projs).from_(exp.to_table(parent_alias))
    if payload.parent_keys and payload.child_keys:
        pairs = list(zip(payload.parent_keys, payload.child_keys, strict=True))
    else:
        # Back-compat: legacy paths without an explicit pairing join by
        # matching names on both sides.
        pairs = [(k, k) for k in sorted(payload.keys, key=str)]
    on = _and(
        [
            exp.EQ(
                this=_ident(p, table=parent_alias),
                expression=_ident(c, table=child_alias),
            )
            for p, c in pairs
        ]
    )
    child_table: exp.Expression = exp.to_table(payload.child_source)
    child_table = exp.alias_(child_table, child_alias, table=True)
    sel = sel.join(child_table, on=on, join_type=join_kind)
    return sel


def _render_enrich_derived(
    parent_alias: str,
    child_alias: str,
    payload: EnrichDerivedPayload,
    parent_columns: tuple[Column, ...],
) -> exp.Select:
    """ENRICH where the child is an upstream PlanStep CTE, not a base table.

    Used by the bridge-resolution planner (``Proposed_OSI_Semantics.md
    §6.5.1``, mid-pipeline form). The shape mirrors :func:`_render_enrich`
    but reads the child as ``child_alias`` rather than from
    ``payload.child_source``. Critically, child columns are projected
    *by name* — the upstream CTE has already materialised them — never
    by re-rendering the original :attr:`Column.expression` (which for a
    pre-aggregated state would re-emit the aggregate function and break
    GROUP BY semantics).
    """
    join_kind = "INNER" if payload.join_type is JoinType.INNER else "LEFT"
    parent_projs: list[exp.Expression] = [
        _ident(c.name, table=parent_alias) for c in parent_columns
    ]
    child_projs: list[exp.Expression] = [
        _ident(col.name, table=child_alias) for col in payload.child_columns
    ]
    sel = exp.select(*parent_projs, *child_projs).from_(exp.to_table(parent_alias))
    pairs = list(zip(payload.parent_keys, payload.child_keys, strict=True))
    on = _and(
        [
            exp.EQ(
                this=_ident(p, table=parent_alias),
                expression=_ident(c, table=child_alias),
            )
            for p, c in pairs
        ]
    )
    sel = sel.join(exp.to_table(child_alias), on=on, join_type=join_kind)
    return sel


def _aggregate_expression(col: Column, parent_alias: str) -> exp.Expression:
    assert col.aggregate is not None
    fn = col.aggregate.function
    arg = _qualify_columns(col.aggregate.argument.expr.copy(), parent_alias)
    if fn is AggregateFunction.SUM:
        return exp.Sum(this=arg)
    if fn is AggregateFunction.COUNT:
        return exp.Count(this=arg)
    if fn is AggregateFunction.COUNT_DISTINCT:
        return exp.Count(this=exp.Distinct(expressions=[arg]))
    if fn is AggregateFunction.MIN:
        return exp.Min(this=arg)
    if fn is AggregateFunction.MAX:
        return exp.Max(this=arg)
    if fn is AggregateFunction.AVG:
        return exp.Avg(this=arg)
    raise OSICodegenError(  # pragma: no cover — StrEnum is exhaustive above
        ErrorCode.E5001_DIALECT_UNSUPPORTED,
        f"unsupported aggregate function {fn!r}",
        context={"function": fn},
    )


def _render_aggregate(
    parent_alias: str,
    payload: AggregatePayload,
    step_columns: tuple[Column, ...],
) -> exp.Select:
    projections: list[exp.Expression] = []
    grain = sorted(payload.new_grain, key=str)
    for g in grain:
        projections.append(_ident(g, table=parent_alias))
    agg_by_name = {c.name: c for c in payload.aggregations}
    for col in step_columns:
        if col.name in payload.new_grain:
            continue
        if col.name in agg_by_name:
            projections.append(
                exp.alias_(
                    _aggregate_expression(agg_by_name[col.name], parent_alias),
                    str(col.name),
                    quoted=False,
                )
            )
    sel = exp.select(*projections).from_(exp.to_table(parent_alias))
    if grain:
        sel = sel.group_by(*(_ident(g, table=parent_alias) for g in grain))
    return sel


def _render_project(parent_alias: str, payload: ProjectPayload) -> exp.Select:
    projections = [_ident(c, table=parent_alias) for c in payload.columns]
    return exp.select(*projections).from_(exp.to_table(parent_alias))


def _render_add_columns(
    parent_alias: str,
    payload: AddColumnsPayload,
    parent_columns: tuple[Column, ...],
) -> exp.Select:
    """Render an ADD_COLUMNS step as ``SELECT parent_cols, <derived…>``.

    The derived expressions already reference columns by their
    parent-CTE-visible name (see
    :func:`~osi.planning.columns.strip_column_qualifiers`), so we only
    need to scope them to ``parent_alias``.
    """
    projections: list[exp.Expression] = [
        _ident(c.name, table=parent_alias) for c in parent_columns
    ]
    for definition in payload.definitions:
        derived = _qualify_columns(definition.expression.expr.copy(), parent_alias)
        projections.append(exp.alias_(derived, str(definition.name), quoted=False))
    return exp.select(*projections).from_(exp.to_table(parent_alias))


def _render_merge(
    step: PlanStep,
    payload: MergePayload,
    left_alias: str,
    right_alias: str,
    left_state: CalculationState,
    right_state: CalculationState,
) -> exp.Select:
    _ = step
    projections: list[exp.Expression] = []
    grain = sorted(payload.on, key=str)
    for g in grain:
        projections.append(
            exp.alias_(
                exp.Coalesce(
                    this=_ident(g, table=left_alias),
                    expressions=[_ident(g, table=right_alias)],
                ),
                str(g),
                quoted=False,
            )
        )
    seen: set[Identifier] = set(payload.on)
    for col in left_state.columns:
        if col.name in seen:
            continue
        projections.append(_ident(col.name, table=left_alias))
        seen.add(col.name)
    for col in right_state.columns:
        if col.name in seen:
            continue
        projections.append(_ident(col.name, table=right_alias))
        seen.add(col.name)

    sel = exp.select(*projections).from_(exp.to_table(left_alias))
    if not grain:
        return sel.join(exp.to_table(right_alias), join_type="CROSS")
    on = _and(
        [
            exp.EQ(
                this=_ident(k, table=left_alias),
                expression=_ident(k, table=right_alias),
            )
            for k in grain
        ]
    )
    return sel.join(exp.to_table(right_alias), on=on, join_type="FULL OUTER")


def _render_filtering_join(
    payload: FilteringJoinPayload,
    left_alias: str,
    right_alias: str,
    left_state: CalculationState,
) -> exp.Select:
    """Render a SEMI / ANTI filtering-join as ``EXISTS`` / ``NOT EXISTS``.

    ``Proposed_OSI_Semantics.md §7.4`` and `§11 #8` require the
    correlated-subquery form. ``IN (SELECT ...)`` is forbidden because
    its NULL semantics differ (``IN`` returns ``UNKNOWN`` when any
    right-side key is NULL while ``EXISTS`` returns FALSE) and a few
    dialects cannot render multi-key ``IN`` against tuples without
    extra parens.
    """
    sel = _pass_through(left_alias, left_state.columns)
    lhs_keys = sorted(payload.lhs_keys, key=str)
    rhs_keys = sorted(payload.rhs_keys, key=str)
    correlation = exp.and_(
        *(
            exp.EQ(
                this=_ident(rk, table=right_alias),
                expression=_ident(lk, table=left_alias),
            )
            for lk, rk in zip(lhs_keys, rhs_keys)
        )
    )
    subquery = (
        exp.select(exp.Literal.number(1))
        .from_(exp.to_table(right_alias))
        .where(correlation)
    )
    pred: exp.Expression = exp.Exists(this=subquery)
    if payload.mode is FilterMode.ANTI:
        pred = exp.Not(this=pred)
    return sel.where(pred)


def _render_step(
    step: PlanStep,
    aliases: dict[int, str],
    steps_by_id: dict[int, PlanStep],
) -> exp.Select:
    parent_alias = aliases[step.inputs[0]] if step.inputs else ""
    if step.operation is PlanOperation.SOURCE:
        assert isinstance(step.payload, SourcePayload)
        return _render_source(step.payload, step.state.columns)
    if step.operation is PlanOperation.FILTER:
        assert isinstance(step.payload, FilterPayload)
        return _render_filter(
            parent_alias,
            step.payload,
            steps_by_id[step.inputs[0]].state.columns,
        )
    if step.operation is PlanOperation.ENRICH:
        if isinstance(step.payload, EnrichDerivedPayload):
            parent_id, child_id = step.inputs
            return _render_enrich_derived(
                aliases[parent_id],
                aliases[child_id],
                step.payload,
                steps_by_id[parent_id].state.columns,
            )
        assert isinstance(step.payload, EnrichPayload)
        return _render_enrich(
            parent_alias,
            step.payload,
            steps_by_id[step.inputs[0]].state.columns,
        )
    if step.operation is PlanOperation.AGGREGATE:
        assert isinstance(step.payload, AggregatePayload)
        return _render_aggregate(parent_alias, step.payload, step.state.columns)
    if step.operation is PlanOperation.PROJECT:
        assert isinstance(step.payload, ProjectPayload)
        return _render_project(parent_alias, step.payload)
    if step.operation is PlanOperation.ADD_COLUMNS:
        assert isinstance(step.payload, AddColumnsPayload)
        return _render_add_columns(
            parent_alias,
            step.payload,
            steps_by_id[step.inputs[0]].state.columns,
        )
    if step.operation is PlanOperation.MERGE:
        assert isinstance(step.payload, MergePayload)
        left_id, right_id = step.inputs
        return _render_merge(
            step,
            step.payload,
            aliases[left_id],
            aliases[right_id],
            steps_by_id[left_id].state,
            steps_by_id[right_id].state,
        )
    if step.operation is PlanOperation.FILTERING_JOIN:
        assert isinstance(step.payload, FilteringJoinPayload)
        left_id, right_id = step.inputs
        return _render_filtering_join(
            step.payload,
            aliases[left_id],
            aliases[right_id],
            steps_by_id[left_id].state,
        )
    raise OSICodegenError(
        ErrorCode.E5001_DIALECT_UNSUPPORTED,
        f"codegen does not handle operation {step.operation!r}",
        context={"operation": step.operation},
    )


def plan_to_select(plan: QueryPlan) -> exp.Select:
    """Build a SQLGlot :class:`Select` from a :class:`QueryPlan`.

    The output is *pre-dialect*: the caller (:mod:`osi.codegen.dialect`)
    applies dialect-specific rewrites before rendering to a string.
    """
    aliases: dict[int, str] = {s.step_id: _step_alias(s.step_id) for s in plan.steps}
    steps_by_id: dict[int, PlanStep] = {s.step_id: s for s in plan.steps}
    ctes: list[exp.CTE] = []
    for step in plan.steps:
        body = _render_step(step, aliases, steps_by_id)
        ctes.append(
            exp.CTE(
                this=body,
                alias=exp.TableAlias(this=exp.to_identifier(aliases[step.step_id])),
            )
        )

    root_alias = aliases[plan.root_step_id]
    root_columns = plan.root.state.columns
    # S-7: thread the optional alias map through the final SELECT so
    # ``column AS alias`` is emitted when the user named a measure
    # something other than the metric's declared name.
    alias_map = dict(plan.output_aliases)
    final = _pass_through(root_alias, root_columns, alias_map=alias_map)
    if plan.order_by:
        # D-029 (amended 2026-05-13): the Foundation default is the
        # SQL:2003 high-end-NULL convention — NULLS LAST for ASC,
        # NULLS FIRST for DESC. NULL is treated as a high-end value and
        # lands at whichever end the maximum lands at, so flipping
        # ASC ↔ DESC also flips NULL placement (the symmetry property).
        # Engines emit the resolved clause explicitly so the cross-engine
        # result is byte-identical (D-014); without this Spark/Databricks
        # would silently use the opposite (low-end-NULL) convention.
        final = final.order_by(
            *(
                exp.Ordered(
                    this=_ident(o.column, table=root_alias),
                    desc=o.descending,
                    nulls_first=o.descending,
                )
                for o in plan.order_by
            )
        )
    if plan.limit is not None:
        final = final.limit(plan.limit)

    final.set("with", exp.With(expressions=ctes))
    return final


__all__ = ["plan_to_select"]
